

# This file was *autogenerated* from the file gen_const_example2.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1 = Integer(1); _sage_const_2 = Integer(2); _sage_const_256 = Integer(256); _sage_const_255 = Integer(255); _sage_const_4 = Integer(4); _sage_const_0 = Integer(0); _sage_const_250 = Integer(250); _sage_const_16 = Integer(16)
i = _sage_const_1 
while i:
    p = random_prime(_sage_const_2 **_sage_const_256 , lbound=_sage_const_2 **_sage_const_255 )
    if mod(p, _sage_const_4 ) != _sage_const_1 :
        continue
    F = GF(p)
    a = int(F.random_element())
    E = EllipticCurve(F, [a, _sage_const_0 ])

    n = E.order()
    fac = n.factor()
    print(fac)

    # on cherche un facteur premier ~256 bits
    for q,e in fac:
        if q.nbits() > _sage_const_250  and q.is_prime():
            r = q
            h = n // r
            if h <= _sage_const_16   :
                print("GOOD CURVE FOUND")
                print("p =", hex(p))
                print("r =", hex(r))
                print("h =", h)
                i = _sage_const_0 

F = GF(p)


P = E.random_point()
while P.order() != r:
    P = E.random_point()

print("a =", hex(a))
print("p =", hex(p))
print("n =", hex(n))
print("P =", hex(P[_sage_const_0 ]),hex(P[_sage_const_1 ]), hex(P[_sage_const_2 ]))
fac = n.factor()
print(fac)

L_moduli = []
L_roots = []

for prime, e in fac:
    modulus = prime**e
    R = Integers(modulus)
    
    if prime == _sage_const_2 :
        # pour 2^e, on teste toutes les valeurs possibles pour x^2+1 mod 2^e
        roots = [x for x in range(modulus) if (x**_sage_const_2  + _sage_const_1 ) % modulus == _sage_const_0 ]
        L_moduli.append(modulus)
        L_roots.append(roots[_sage_const_0 ])  # on prend une solution parmi celles possibles
        continue
    
    # pour les autres nombres premiers
    x = R(-_sage_const_1 ).sqrt(all=True, extend=False)[_sage_const_0 ]  # racine de -1 mod p^e
    L_moduli.append(modulus)
    L_roots.append(Integer(x))

# Combiner toutes les solutions avec CRT
racine = crt(L_roots, L_moduli)
print("lambda = ", hex(racine))

