

# This file was *autogenerated* from the file gen_const_example3.sage
from sage.all_cmdline import *   # import sage library

_sage_const_2 = Integer(2); _sage_const_256 = Integer(256); _sage_const_255 = Integer(255); _sage_const_7 = Integer(7); _sage_const_1 = Integer(1); _sage_const_0xe6adac14aa1890c61edfaeb1f66359f6468e064f93ce403cfb73b9e3cb7f44ad = Integer(0xe6adac14aa1890c61edfaeb1f66359f6468e064f93ce403cfb73b9e3cb7f44ad); _sage_const_0 = Integer(0); _sage_const_3 = Integer(3); _sage_const_4 = Integer(4)
p = random_prime(_sage_const_2 **_sage_const_256 , lbound=_sage_const_2 **_sage_const_255 )
while kronecker(-_sage_const_7 , p) == -_sage_const_1 :
    p = random_prime(_sage_const_2 **_sage_const_256 , lbound=_sage_const_2 **_sage_const_255 )

p = _sage_const_0xe6adac14aa1890c61edfaeb1f66359f6468e064f93ce403cfb73b9e3cb7f44ad 

F = GF(p)
E = EllipticCurve(F, [_sage_const_0 , _sage_const_0 , -_sage_const_3 /_sage_const_4 , -_sage_const_2 , -_sage_const_1 ])

n = E.order()

print("p =", hex(p))
print("n =", hex(n))

fac = n.factor()
for p,e in fac:
    if p == _sage_const_2 :
        continue
    print(p, kronecker(-_sage_const_7 , p))
print(fac)

P = E.random_point()
while P.order() != n:
    P = E.random_point()
print("P =", hex(P[_sage_const_0 ]), hex(P[_sage_const_1 ]), hex(P[_sage_const_2 ]))
print(n*P)

L_moduli = []
L_roots = []

for prime, e in fac:
    modulus = prime**e
    R = Integers(modulus)

    if prime == _sage_const_2 :
        # pour 2^e, on teste toutes les valeurs possibles pour x^2-x+2 mod 2^e
        roots = [x for x in range(modulus) if (x**_sage_const_2  - x + _sage_const_2 ) % modulus == _sage_const_0 ]
        L_moduli.append(modulus)
        L_roots.append(roots[_sage_const_0 ])  # on prend une solution parmi celles possibles
        continue

    # pour les autres nombres premiers
    s = R(-_sage_const_7 ).sqrt(all=True, extend=False)[_sage_const_0 ]  # racine de -7 mod p^e
    inv2 = R(_sage_const_2 )**-_sage_const_1                          # inverse de 2 modulo p^e
    x = (_sage_const_1  + s) * inv2                     # solution x = (1 + sqrt(-7))/2 mod p^e
    L_moduli.append(modulus)
    L_roots.append(Integer(x))

# Combiner toutes les solutions avec CRT
racine = crt(L_roots, L_moduli)
print("lambda = ", hex(racine))

