

# This file was *autogenerated* from the file gen_const_example3.sage
from sage.all_cmdline import *   # import sage library

_sage_const_2 = Integer(2); _sage_const_256 = Integer(256); _sage_const_255 = Integer(255); _sage_const_7 = Integer(7); _sage_const_0 = Integer(0); _sage_const_3 = Integer(3); _sage_const_4 = Integer(4); _sage_const_1 = Integer(1)
p = random_prime(_sage_const_2 **_sage_const_256 , lbound=_sage_const_2 **_sage_const_255 )
while not is_square(-_sage_const_7 , p):
    p = random_prime(_sage_const_2 **_sage_const_256 , lbound=_sage_const_2 **_sage_const_255 )

F = GF(p)
E = EllipticCurve(F, [_sage_const_0 , _sage_const_0 , -_sage_const_3 /_sage_const_4 , -_sage_const_2 , -_sage_const_1 ])

n = E.order()
#h = n.factor()[0][0]  # cofacteur petit

P = E.random_point()
while P.order() != n:
    P = E.random_point()


print("p =", hex(p))
print("n =", hex(n))
print(n.is_prime())
#print("h =", hex(h))
print("P=", hex(P[_sage_const_0 ]),hex(P[_sage_const_1 ]), hex(P[_sage_const_2 ]))
print(n.factor())

