

# This file was *autogenerated* from the file gen_const_example2.sage
from sage.all_cmdline import *   # import sage library

_sage_const_2 = Integer(2); _sage_const_256 = Integer(256); _sage_const_255 = Integer(255); _sage_const_4 = Integer(4); _sage_const_1 = Integer(1); _sage_const_0xb4fc23d83418e4d099141c1a435cbb663817e03477f8f84f3afd51e63e89ef31 = Integer(0xb4fc23d83418e4d099141c1a435cbb663817e03477f8f84f3afd51e63e89ef31); _sage_const_0x2e818c97303c2c8e6ee49e2b6cacc754eff27e8346e4a23da9b7b882685b7c72 = Integer(0x2e818c97303c2c8e6ee49e2b6cacc754eff27e8346e4a23da9b7b882685b7c72); _sage_const_0 = Integer(0)
p = random_prime(_sage_const_2 **_sage_const_256 , lbound=_sage_const_2 **_sage_const_255 )
while mod(p, _sage_const_4 ) != _sage_const_1 :
    p = random_prime(_sage_const_2 **_sage_const_256 , lbound=_sage_const_2 **_sage_const_255 )

p = _sage_const_0xb4fc23d83418e4d099141c1a435cbb663817e03477f8f84f3afd51e63e89ef31 
F = GF(p)

a = int(F.random_element())
a = _sage_const_0x2e818c97303c2c8e6ee49e2b6cacc754eff27e8346e4a23da9b7b882685b7c72 
E = EllipticCurve(F, [a, _sage_const_0 ])

n = E.order()

P = E.random_point()
while P.order() != n:
    P = E.random_point()

print("a =", hex(a))
print("p =", hex(p))
print("n =", hex(n))
print("P =", hex(P[_sage_const_0 ]),hex(P[_sage_const_1 ]), hex(P[_sage_const_2 ]))
fac = n.factor()
print(fac)

L_moduli = []
L_roots = []

for prime, e in fac:
    modulus = prime**e
    R = Integers(modulus)
    
    if prime == _sage_const_2 :
        # pour 2^e, on teste toutes les valeurs possibles pour x^2+1 mod 2^e
        roots = [x for x in range(modulus) if (x**_sage_const_2  + _sage_const_1 ) % modulus == _sage_const_0 ]
        L_moduli.append(modulus)
        L_roots.append(roots[_sage_const_0 ])  # on prend une solution parmi celles possibles
        continue
    
    # pour les autres nombres premiers
    x = R(-_sage_const_1 ).sqrt(all=True, extend=False)[_sage_const_0 ]  # racine de -1 mod p^e
    L_moduli.append(modulus)
    L_roots.append(Integer(x))

# Combiner toutes les solutions avec CRT
racine = crt(L_roots, L_moduli)
print("lambda = ", hex(racine))

